In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [57]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_blobs
from collections import Counter
from path import Path
import hvplot.pandas

# importing files for w/l

In [133]:
df_2019 = pd.read_csv(Path("random.txt"))
df_2019 = df_2019[["Opp", "Result", "Starting Pitcher", "Opposing Pitcher", "Game Date"]]

true_w = df_2019["Result"].str.contains('W', na=True)
count = 0
Result = []
for row in df_2019.index:
    if true_w[row]:
        Result.append(1)
    else:
        Result.append(0)
        
df_2019["Result"] = Result
df_2019 = df_2019.set_index("Opp")

df_2019

     Result  Starting Pitcher  Opposing Pitcher   Game Date
Opp
TBA       1  Justin Verlander       Blake Snell  2019-03-28
TBA       0       Gerrit Cole    Charlie Morton  2019-03-29
TBA       0     Collin McHugh     Tyler Glasnow  2019-03-30
TBA       0        Wade Miley    Yonny Chirinos  2019-03-31
TEX       1      Brad Peacock        Drew Smyly  2019-04-01
..      ...               ...               ...         ...
SEA       1      Zack Greinke     Yusei Kikuchi  2019-09-25
ANA       0        Wade Miley      Jaime Barria  2019-09-26
ANA       1      Jose Urquidy  Patrick Sandoval  2019-09-27
ANA       1  Justin Verlander       Jose Suarez  2019-09-28
ANA       1       Gerrit Cole     Dillon Peters  2019-09-29

[162 rows x 4 columns]

In [134]:
df_2018 = pd.read_csv(Path("2018result.txt"))
df_2018 = df_2018[["Opp", "Result", "Starting Pitcher", "Opposing Pitcher", "Game Date"]]

true_w = df_2018["Result"].str.contains('W', na=True)
count = 0
Result = []
for row in df_2018.index:
    if true_w[row]:
        Result.append(1)
    else:
        Result.append(0)
        
df_2018["Result"] = Result
df_2018 = df_2018.set_index("Opp")

df_2018

     Result  Starting Pitcher Opposing Pitcher   Game Date
Opp
TEX       1  Justin Verlander      Cole Hamels  2018-03-29
TEX       0    Dallas Keuchel      Doug Fister  2018-03-30
TEX       1   Lance McCullers       Matt Moore  2018-03-31
TEX       1       Gerrit Cole       Mike Minor  2018-04-01
BAL       1    Charlie Morton    Chris Tillman  2018-04-02
..      ...               ...              ...         ...
TOR       0    Chris Devenski  Sean Reid-Foley  2018-09-26
BAL       1       Gerrit Cole       David Hess  2018-09-28
BAL       1  Justin Verlander      Dylan Bundy  2018-09-29
BAL       1    Dallas Keuchel    Yefry Ramirez  2018-09-29
BAL       0    Charlie Morton  Jimmy Yacabonis  2018-09-30

[162 rows x 4 columns]

In [135]:
df_combined = pd.concat([df_2019,df_2018])
df_combined

     Result  Starting Pitcher Opposing Pitcher   Game Date
Opp
TBA       1  Justin Verlander      Blake Snell  2019-03-28
TBA       0       Gerrit Cole   Charlie Morton  2019-03-29
TBA       0     Collin McHugh    Tyler Glasnow  2019-03-30
TBA       0        Wade Miley   Yonny Chirinos  2019-03-31
TEX       1      Brad Peacock       Drew Smyly  2019-04-01
..      ...               ...              ...         ...
TOR       0    Chris Devenski  Sean Reid-Foley  2018-09-26
BAL       1       Gerrit Cole       David Hess  2018-09-28
BAL       1  Justin Verlander      Dylan Bundy  2018-09-29
BAL       1    Dallas Keuchel    Yefry Ramirez  2018-09-29
BAL       0    Charlie Morton  Jimmy Yacabonis  2018-09-30

[324 rows x 4 columns]

# importing pitching data

In [61]:
df_pitch_2019 = pd.read_csv(Path("mlb-player-stats-P.csv"))
df_pitch_2019.set_index(["Player"], inplace = True)
df_pitch_2019 = df_pitch_2019.drop(columns = ["Team"])
df_pitch_2019 = df_pitch_2019.groupby(level=0).mean()

df_pitch_2019.head(10)

,Age,G,GS,CG,SHO,IP,H,ER,K,BB,HR,W,L,SV,BS,HLD,ERA,WHIP
Player,,,,,,,,,,,,,,,,,,
A.J. Cole,28.0,25.0,0.0,0.0,0.0,26.00,31.0,11.0,30.0,8.0,4.0,3.0,1.0,1.0,0.0,0.0,3.810,1.50
A.J. Minter,27.0,36.0,0.0,0.0,0.0,29.10,36.0,23.0,35.0,23.0,3.0,3.0,4.0,5.0,2.0,6.0,7.060,2.01
A.J. Puk,25.0,10.0,0.0,0.0,0.0,11.10,10.0,4.0,13.0,5.0,1.0,2.0,0.0,0.0,1.0,2.0,3.180,1.32
Aaron Barrett,32.0,3.0,0.0,0.0,0.0,2.10,5.0,4.0,1.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,15.430,3.86
Aaron Brooks,30.0,14.5,9.0,0.0,0.0,54.65,59.0,34.5,41.0,17.0,10.5,3.0,4.0,0.0,0.0,0.0,5.595,1.37
Aaron Bummer,27.0,58.0,0.0,0.0,0.0,67.20,43.0,16.0,60.0,24.0,4.0,0.0,0.0,1.0,2.0,27.0,2.130,0.99
Aaron Civale,25.0,10.0,10.0,0.0,0.0,57.20,44.0,15.0,46.0,16.0,4.0,3.0,4.0,0.0,0.0,0.0,2.340,1.04
Aaron Loup,32.0,4.0,0.0,0.0,0.0,3.10,2.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000,0.90
Aaron Nola,27.0,34.0,34.0,0.0,0.0,202.10,176.0,87.0,229.0,80.0,27.0,12.0,7.0,0.0,0.0,0.0,3.870,1.27
Aaron Sanchez,28.0,13.5,13.5,0.0,0.0,65.20,72.5,43.0,57.5,34.0,10.0,2.5,7.0,0.0,0.0,0.0,5.445,1.46

In [62]:
from sklearn.cluster import KMeans

inertia = []
k = list(range(1, 11))

for i in k:
    km = KMeans(n_clusters=i, random_state=5)
    km.fit(df_pitch_2019)
    inertia.append(km.inertia_)

# Define a DataFrame to plot the Elbow Curve using hvPlot
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", title="Elbow Curve", xticks=k)

:Curve   [k]   (inertia)

In [63]:
model = KMeans(n_clusters=3, random_state=7)
model.fit(df_pitch_2019)
predictions = model.predict(df_pitch_2019)
df_pitch_2019["class"] = model.labels_
df_pitch_2019.head()

,Age,G,GS,CG,SHO,IP,H,ER,K,BB,HR,W,L,SV,BS,HLD,ERA,WHIP,class
Player,,,,,,,,,,,,,,,,,,,
A.J. Cole,28.0,25.0,0.0,0.0,0.0,26.00,31.0,11.0,30.0,8.0,4.0,3.0,1.0,1.0,0.0,0.0,3.810,1.50,0
A.J. Minter,27.0,36.0,0.0,0.0,0.0,29.10,36.0,23.0,35.0,23.0,3.0,3.0,4.0,5.0,2.0,6.0,7.060,2.01,0
A.J. Puk,25.0,10.0,0.0,0.0,0.0,11.10,10.0,4.0,13.0,5.0,1.0,2.0,0.0,0.0,1.0,2.0,3.180,1.32,0
Aaron Barrett,32.0,3.0,0.0,0.0,0.0,2.10,5.0,4.0,1.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,15.430,3.86,0
Aaron Brooks,30.0,14.5,9.0,0.0,0.0,54.65,59.0,34.5,41.0,17.0,10.5,3.0,4.0,0.0,0.0,0.0,5.595,1.37,2

In [64]:
df_pitch_2018 = pd.read_csv(Path("mlb-player-stats-P2018.csv"))
df_pitch_2018.set_index(["Player"], inplace = True)
df_pitch_2018 = df_pitch_2018.drop(columns = ["Team"])
df_pitch_2018 = df_pitch_2018.groupby(level=0).mean()

df_pitch_2018.head(7)

,Age,G,GS,CG,SHO,IP,H,ER,K,BB,HR,W,L,SV,BS,HLD,ERA,WHIP
Player,,,,,,,,,,,,,,,,,,
A.J. Cole,28.0,16.0,1.0,0.0,0.0,24.05,27.5,16.5,29.5,11.0,7.5,2.0,1.0,0.0,0.5,0.0,8.66,1.790
A.J. Minter,27.0,65.0,0.0,0.0,0.0,61.10,57.0,22.0,69.0,22.0,3.0,4.0,3.0,15.0,2.0,12.0,3.23,1.290
AJ Ramos,34.0,28.0,0.0,0.0,0.0,19.20,17.0,14.0,22.0,15.0,3.0,2.0,2.0,0.0,0.0,7.0,6.41,1.630
Aaron Brooks,30.0,3.0,0.0,0.0,0.0,2.20,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.130
Aaron Bummer,27.0,37.0,0.0,0.0,0.0,31.20,40.0,15.0,35.0,10.0,1.0,0.0,1.0,0.0,1.0,2.0,4.26,1.580
Aaron Loup,32.0,29.5,0.0,0.0,0.0,19.60,24.0,10.0,22.0,7.0,2.0,0.0,0.0,0.0,0.0,5.5,4.52,1.425
Aaron Nola,27.0,33.0,33.0,0.0,0.0,212.10,149.0,56.0,224.0,58.0,17.0,17.0,6.0,0.0,0.0,0.0,2.37,0.970

In [65]:
inertia = []
k = list(range(1, 11))

# Looking for the best k
for i in k:
    km = KMeans(n_clusters=i, random_state=5)
    km.fit(df_pitch_2018)
    inertia.append(km.inertia_)

# Define a DataFrame to plot the Elbow Curve using hvPlot
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", title="Elbow Curve", xticks=k)

:Curve   [k]   (inertia)

In [66]:
model = KMeans(n_clusters=3, random_state=7)
model.fit(df_pitch_2018)
predictions = model.predict(df_pitch_2018)
df_pitch_2018["class"] = model.labels_
df_pitch_2018.head()

,Age,G,GS,CG,SHO,IP,H,ER,K,BB,HR,W,L,SV,BS,HLD,ERA,WHIP,class
Player,,,,,,,,,,,,,,,,,,,
A.J. Cole,28.0,16.0,1.0,0.0,0.0,24.05,27.5,16.5,29.5,11.0,7.5,2.0,1.0,0.0,0.5,0.0,8.66,1.79,0
A.J. Minter,27.0,65.0,0.0,0.0,0.0,61.10,57.0,22.0,69.0,22.0,3.0,4.0,3.0,15.0,2.0,12.0,3.23,1.29,2
AJ Ramos,34.0,28.0,0.0,0.0,0.0,19.20,17.0,14.0,22.0,15.0,3.0,2.0,2.0,0.0,0.0,7.0,6.41,1.63,0
Aaron Brooks,30.0,3.0,0.0,0.0,0.0,2.20,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.13,0
Aaron Bummer,27.0,37.0,0.0,0.0,0.0,31.20,40.0,15.0,35.0,10.0,1.0,0.0,1.0,0.0,1.0,2.0,4.26,1.58,0

In [67]:
df_pitch_combined = pd.concat([df_pitch_2018, df_pitch_2019])

In [68]:
df_pitch_combined = df_pitch_combined.groupby(level=0).mean()
df_pitch_combined = df_pitch_combined.drop(columns = ["class"])

In [69]:
inertia = []
k = list(range(1, 11))

# Looking for the best k
for i in k:
    km = KMeans(n_clusters=i, random_state=5)
    km.fit(df_pitch_combined)
    inertia.append(km.inertia_)

# Define a DataFrame to plot the Elbow Curve using hvPlot
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", title="Elbow Curve", xticks=k)

:Curve   [k]   (inertia)

In [70]:
model = KMeans(n_clusters=3, random_state=7)
model.fit(df_pitch_combined)
predictions = model.predict(df_pitch_combined)
df_pitch_combined["class"] = model.labels_
df_pitch_combined.head()

,Age,G,GS,CG,SHO,IP,H,ER,K,BB,HR,W,L,SV,BS,HLD,ERA,WHIP,class
Player,,,,,,,,,,,,,,,,,,,
A.J. Cole,28.0,20.5,0.5,0.0,0.0,25.025,29.25,13.75,29.75,9.5,5.75,2.5,1.0,0.5,0.25,0.0,6.235,1.645,1
A.J. Minter,27.0,50.5,0.0,0.0,0.0,45.100,46.50,22.50,52.00,22.5,3.00,3.5,3.5,10.0,2.00,9.0,5.145,1.650,2
A.J. Puk,25.0,10.0,0.0,0.0,0.0,11.100,10.00,4.00,13.00,5.0,1.00,2.0,0.0,0.0,1.00,2.0,3.180,1.320,1
AJ Ramos,34.0,28.0,0.0,0.0,0.0,19.200,17.00,14.00,22.00,15.0,3.00,2.0,2.0,0.0,0.00,7.0,6.410,1.630,1
Aaron Barrett,32.0,3.0,0.0,0.0,0.0,2.100,5.00,4.00,1.00,4.0,1.00,0.0,0.0,0.0,0.00,0.0,15.430,3.860,1

In [154]:
df_pitch_combined.to_csv(Path("df_pitch.csv"), index = True, header=True)

# importing batter data

In [104]:
# df_bat_2019 = pd.read_csv(Path("mlb-player-stats-Batters.csv"))
# df_bat_2019 = df_bat_2019.drop(columns = ["Player"])

# df_bat_2019 = df_bat_2019.groupby(by = "Team").mean()
# # df_bat_2019 = df_bat_2019[["SO", "AVG", "HBP", "SH", "HR", "RBI", "R", "H"]]
# # df_bat_2019

# df_bat_2019.to_csv(Path("df_bat_2019.csv"), index = True, header=True)

In [105]:
# df_bat_2018 = pd.read_csv(Path("mlb-player-stats-Batters2018.csv"))
# df_bat_2018 = df_bat_2018.drop(columns = ["Player"])

# df_bat_2018 = df_bat_2018.groupby(by = "Team").mean()
# # df_bat_2018 = df_bat_2018[["SO", "AVG", "HBP", "SH", "HR", "RBI", "R", "H"]]
# # df_bat_2018.head()
# df_bat_2018.to_csv(Path("df_bat_2018.csv"), index = True, header=True)

In [115]:
df_bat_2018 = pd.read_csv(Path("df_bat_2018.csv"))
df_bat_2019 = pd.read_csv(Path("df_bat_2019.csv"))

In [116]:
df_bat_2019.set_index("Team",inplace=True)
df_bat_2018.set_index("Team",inplace=True)

In [117]:
df_bat_2019

,Age,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,SH,SF,HBP,AVG,OBP,SLG,OPS
Team,,,,,,,,,,,,,,,,,,,,
ARI,29.666667,80.952381,254.142857,37.714286,66.000000,13.523810,1.857143,10.238095,35.952381,4.142857,0.666667,25.380952,57.857143,0.238095,1.857143,3.333333,0.232333,0.306571,0.403762,0.710333
ATL,29.800000,83.300000,262.650000,41.950000,70.050000,13.550000,1.450000,12.450000,40.500000,4.450000,1.400000,30.550000,65.400000,0.150000,1.700000,2.900000,0.237550,0.314150,0.420600,0.734750
BAL,27.875000,70.708333,232.541667,30.333333,57.416667,10.500000,1.041667,8.875000,29.083333,3.500000,1.250000,19.208333,59.583333,0.791667,1.541667,2.958333,0.210417,0.280833,0.341958,0.622792
BOS,29.857143,79.095238,273.761905,42.809524,73.952381,16.428571,1.285714,11.666667,40.761905,3.238095,1.428571,28.095238,65.285714,0.857143,2.095238,2.333333,0.229381,0.299381,0.375381,0.674762
CHN,29.391304,73.478261,224.086956,34.869565,58.217391,11.434783,1.130435,11.086957,33.043478,1.956522,1.043478,24.695652,57.260870,0.304348,1.608696,3.521739,0.221609,0.300130,0.389957,0.690087
CIN,29.478261,75.260870,223.000000,29.652174,55.869565,10.000000,1.130435,9.782609,28.956522,3.260870,1.565217,20.956522,55.782609,0.086957,1.434783,3.869565,0.248522,0.321304,0.418913,0.740217
CLE,28.807692,63.076923,208.000000,29.576923,52.038462,11.000000,0.692308,8.576923,28.115385,3.961538,1.346154,21.653846,50.846154,1.461538,1.769231,1.923077,0.203654,0.275654,0.352346,0.628000
COL,29.428571,80.666667,256.904762,39.000000,69.809524,15.190476,1.904762,10.666667,37.190476,3.380952,1.476190,22.666667,65.428571,0.428571,2.047619,2.047619,0.233238,0.293667,0.402333,0.696000
CHA,28.590909,73.454545,250.500000,32.181818,65.545455,11.818182,0.909091,8.272727,30.636364,2.863636,1.272727,17.181818,69.863636,1.545455,1.454545,3.000000,0.228727,0.287091,0.350727,0.637818
DET,28.636364,71.772727,251.181818,26.363636,60.409091,13.272727,1.863636,6.772727,25.272727,2.590909,0.909091,17.772727,71.818182,0.409091,1.909091,2.181818,0.216045,0.270000,0.347227,0.617227
HOU,28.904762,79.047619,266.380952,43.761905,73.190476,15.380952,1.333333,13.714286,42.428571,3.190476,1.238095,30.666667,55.000000,0.428571,2.714286,3.142857,0.250619,0.328667,0.447095,0.775762
KCA,28.125000,66.291667,228.208333,28.791667,56.416667,11.708333,1.666667,6.750000,27.250000,4.875000,1.625000,18.958333,58.208333,0.916667,1.750000,2.458333,0.227708,0.289875,0.348083,0.637958
ANA,29.740741,62.111111,204.592593,28.481481,50.629630,9.925926,0.777778,8.148148,27.185185,2.407407,0.740741,21.666667,46.962963,0.148148,1.555556,2.481481,0.199556,0.276704,0.334630,0.611333
LAN,29.500000,77.454545,236.090909,39.500000,62.136364,13.409091,0.909091,12.590909,38.363636,2.590909,0.454545,27.000000,56.181818,0.090909,2.045455,3.681818,0.228409,0.303000,0.411818,0.714818
MIA,29.480000,67.840000,210.080000,24.240000,51.920000,10.400000,0.720000,5.840000,23.280000,2.200000,1.200000,15.560000,52.640000,0.320000,1.320000,2.840000,0.221360,0.275520,0.347880,0.623400
MIL,29.238095,83.523810,250.952381,36.047619,63.285714,12.904762,0.809524,11.809524,34.761905,4.809524,1.190476,29.523810,67.428571,0.238095,1.809524,3.428571,0.229952,0.317476,0.414619,0.732095
MIN,28.900000,81.750000,285.900000,46.850000,77.350000,15.900000,1.150000,15.350000,45.300000,1.400000,1.050000,26.150000,66.300000,0.350000,2.050000,4.050000,0.254000,0.327150,0.455900,0.783050
NYN,30.083333,74.000000,221.250000,32.083333,58.041667,11.458333,0.708333,9.833333,31.250000,2.333333,1.125000,21.041667,51.916667,0.458333,1.083333,3.875000,0.202083,0.270208,0.342042,0.612250
NYA,29.541667,66.916667,231.708333,39.250000,62.208333,12.083333,0.708333,12.750000,37.625000,2.291667,0.916667,23.708333,59.208333,0.250000,1.375000,2.041667,0.245917,0.321708,0.448333,0.770042
OAK,29.434783,71.956522,240.869565,36.695652,59.913043,12.695652,1.000000,11.173913,34.739130,2.130435,0.913043,25.086957,57.826087,0.260870,1.565217,3.782609,0.223174,0.299304,0.407913,0.707217
PHI,29.000000,68.320000,212.000000,30.320000,53.400000,12.280000,1.040000,8.560000,29.240000,3.120000,0.720000,21.920000,52.520000,0.440000,1.360000,2.280000,0.199000,0.256240,0.353800,0.610040
PIT,29.217391,74.347826,234.304348,32.086957,63.260870,13.565217,1.608696,7.043478,30.739130,2.782609,1.260870,18.000000,47.826087,0.739130,1.434783,2.695652,0.243826,0.300348,0.373391,0.673739
SDN,27.409091,77.727273,233.863636,30.545455,56.909091,10.000000,1.090909,9.954545,29.272727,3.181818,1.636364,22.681818,66.045455,0.318182,1.409091,2.454545,0.226045,0.295409,0.364955,0.660364
SEA,29.629630,61.148148,203.000000,28.037037,48.296296,9.370370,1.037037,8.851852,27.037037,4.259259,1.740741,21.703704,58.074074,0.407407,1.370370,2.148148,0.206259,0.290370,0.359926,0.650296
SFN,29.937500,54.250000,166.218750,20.937500,40.750000,9.281250,0.812500,5.156250,20.218750,1.468750,0.875000,14.437500,39.812500,0.187500,1.312500,1.531250,0.196125,0.259062,0.310250,0.569312
SLN,28.904762,81.190476,246.428571,35.619048,61.809524,11.333333,1.142857,10.000000,33.380952,5.476190,1.333333,26.428571,61.714286,0.428571,1.761905,3.571429,0.233810,0.304381,0.388571,0.692952
TBA,28.576923,65.076923,215.576923,29.500000,54.769231,11.192308,1.115385,8.307692,28.000000,3.615385,1.423077,20.807692,56.961538,0.307692,1.307692,2.807692,0.236462,0.293769,0.393846,0.687615
TEX,29.526316,84.894737,290.473684,42.631579,72.263158,15.578947,1.263158,11.736842,40.263158,6.894737,2.000000,28.000000,82.315789,0.842105,2.315789,3.526316,0.237842,0.306947,0.410684,0.717632
TOR,27.250000,66.833333,228.208333,30.166667,54.041667,11.250000,0.875000,10.291667,29.041667,2.125000,0.833333,21.166667,62.666667,0.583333,1.166667,1.875000,0.207583,0.266583,0.364167,0.630750
WAS,29.476190,77.761905,247.666667,40.619048,67.571429,14.095238,1.285714,10.952381,38.380952,5.428571,1.380952,27.380952,55.857143,0.904762,2.000000,3.857143,0.239952,0.305714,0.392952,0.698667

In [118]:
df_bat_combined = pd.concat([df_bat_2018, df_bat_2019])
df_bat_combined = df_bat_combined.groupby(level=0).mean()
df_bat_combined = df_bat_combined[["SO", "AVG", "HBP", "SH", "HR", "RBI", "R", "H"]]

df_bat_combined.head()

,SO,AVG,HBP,SH,HR,RBI,R,H
Team,,,,,,,,
ANA,47.388889,0.217889,2.592593,0.203704,8.037037,26.370370,27.574074,49.796296
ARI,59.064935,0.224326,2.848485,0.346320,9.119048,32.589827,34.311688,61.340909
ATL,56.345833,0.223087,2.825000,0.345833,9.850000,34.937500,36.516667,64.400000
BAL,54.863095,0.215548,2.497024,0.610119,7.794643,25.130952,26.220238,52.190476
BOS,63.717857,0.233665,2.541667,0.603571,11.033333,41.030952,43.204762,74.601190

In [119]:
df_hou = df_bat_combined.loc["HOU"]
df_hou = pd.DataFrame(df_hou)
df_hou = df_hou.transpose()
df_hou.rename(columns = {
    "SO" : "Astros-SO", 
    "AVG" : "Astros-AVG", 
    "HBP" : "Astros-HBP", 
    "SH" : "Astros-SH", 
    "HR" : "Astros-HR", 
    "RBI" : "Astros-RBI", 
    "R" : "Astros-R", 
    "H" : "Astros-H"
}, inplace=True)
df_hou.head()

,Astros-SO,Astros-AVG,Astros-HBP,Astros-SH,Astros-HR,Astros-RBI,Astros-R,Astros-H
HOU,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238

In [78]:
df_hou['key'] = 1
merge['key'] = 1
df = pd.merge(df_hou, merge, on='key')
del df['key']

# Home/Away Data

In [137]:
df_home_2018 = pd.read_csv(Path("2018wl.txt"))
df_home_2019 = pd.read_csv(Path("2019wl.txt"))
df_home_2018.head()

,Game#,Game Date,Seq,Team,Lg,Opp,LgOpp,Hm/Aw,TimeDay,Att,...,Record,Div Rk,Lg Rk,MLB Rk,GBL,Strk,Winning Pitcher,Losing Pitcher,Save Pitcher,Home Runs
0,1,2018-03-29,-,HOU,AL,TEX,AL,Away,Day,"47,253",...,1-0,1,5,6,--,W1,Justin Verlander,Cole Hamels,---,"Marisnick, Springer"
1,2,2018-03-30,-,HOU,AL,TEX,AL,Away,Night,"35,469",...,1-1,3,8,19,0.5,L1,Doug Fister,Dallas Keuchel,---,---
2,3,2018-03-31,-,HOU,AL,TEX,AL,Away,Day,"36,892",...,2-1,2,5,9,--,W1,Lance McCullers,Matt Moore,---,"Correa, Marisnick"
3,4,2018-04-01,-,HOU,AL,TEX,AL,Away,Day,"26,758",...,3-1,2,4,7,--,W2,Gerrit Cole,Mike Minor,---,---
4,5,2018-04-02,-,HOU,AL,BAL,AL,Home,Night,"42,675",...,4-1,1,2,3,--,W3,Charlie Morton,Chris Tillman,---,Gonzalez

In [138]:
df_home_2019 = df_home_2019[["Hm/Aw", "Opp", "Game Date"]]
df_home_2019 = df_home_2019.set_index("Opp")

df_home_2018 = df_home_2018[["Hm/Aw", "Opp", "Game Date"]]
df_home_2018 = df_home_2018.set_index("Opp")

In [139]:
df_home_away_merge = pd.concat([df_home_2019, df_home_2018])

In [140]:
df_home_away_merge

    Hm/Aw   Game Date
Opp
TBA  Away  2019-03-28
TBA  Away  2019-03-29
TBA  Away  2019-03-30
TBA  Away  2019-03-31
TEX  Away  2019-04-01
..    ...         ...
TOR  Away  2018-09-26
BAL  Away  2018-09-28
BAL  Away  2018-09-29
BAL  Away  2018-09-29
BAL  Away  2018-09-30

[323 rows x 2 columns]

In [143]:
df_combined.reset_index(inplace = True)

In [145]:
df_home_away_merge.reset_index(inplace = True)

In [149]:
df_home_away_merge = df_home_away_merge.set_index("Game Date")
df_combined = df_combined.set_index("Game Date")

In [152]:
merge = pd.merge(df_combined, df_home_away_merge, left_index=True, right_index=True)

merge.dropna(inplace=True)
merge

           Opp_x  Result  Starting Pitcher  Opposing Pitcher Opp_y Hm/Aw
Game Date
2018-03-29   TEX       1  Justin Verlander       Cole Hamels   TEX  Away
2018-03-30   TEX       0    Dallas Keuchel       Doug Fister   TEX  Away
2018-03-31   TEX       1   Lance McCullers        Matt Moore   TEX  Away
2018-04-01   TEX       1       Gerrit Cole        Mike Minor   TEX  Away
2018-04-02   BAL       1    Charlie Morton     Chris Tillman   BAL  Home
...          ...     ...               ...               ...   ...   ...
2019-09-25   SEA       1      Zack Greinke     Yusei Kikuchi   SEA  Away
2019-09-26   ANA       0        Wade Miley      Jaime Barria   ANA  Away
2019-09-27   ANA       1      Jose Urquidy  Patrick Sandoval   ANA  Away
2019-09-28   ANA       1  Justin Verlander       Jose Suarez   ANA  Away
2019-09-29   ANA       1       Gerrit Cole     Dillon Peters   ANA  Away

[327 rows x 6 columns]

In [153]:
merge.to_csv(Path("Results.csv"), index = True, header=True)

# combining all the dataframes

In [129]:
merge = pd.merge(df_combined, df_bat_combined, left_index=True, right_index=True)
# merge = pd.merge(merge, df_home_away_merge, left_index=True, right_index=True)
merge

,Result,Starting Pitcher,Opposing Pitcher,SO,AVG,HBP,SH,HR,RBI,R,H
ANA,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296
ANA,1,Justin Verlander,Matt Harvey,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296
ANA,0,Justin Verlander,Noe Ramirez,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296
ANA,1,Gerrit Cole,Andrew Heaney,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296
ANA,1,Jose Urquidy,Jose Suarez,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296
...,...,...,...,...,...,...,...,...,...,...,...
TOR,1,Charlie Morton,Ryan Borucki,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690
TOR,1,Dallas Keuchel,Marco Estrada,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690
TOR,1,Dallas Keuchel,Marco Estrada,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690
TOR,1,Joshua James,Sam Gaviglio,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690
TOR,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690

In [128]:
merge["HM/AW"] =

,Result,Starting Pitcher,Opposing Pitcher,SO,AVG,HBP,SH,HR,RBI,R,H,Hm/Aw
0,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296,Away
1,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296,Away
2,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296,Away
3,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296,Away
4,1,Wade Miley,Trevor Cahill,47.388889,0.217889,2.592593,0.203704,8.037037,26.37037,27.574074,49.796296,Away
...,...,...,...,...,...,...,...,...,...,...,...,...
1243067,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690,Home
1243068,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690,Home
1243069,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690,Home
1243070,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690,Home
1243071,0,Chris Devenski,Sean Reid-Foley,55.851190,0.216542,1.973214,0.380952,9.020833,26.66369,27.708333,50.788690,Home

In [83]:
df_hou['key'] = 1
merge['key'] = 1
df = pd.merge(df_hou, merge, on='key')
del df['key']
merge = df

In [100]:
df_hou

,Astros-SO,Astros-AVG,Astros-HBP,Astros-SH,Astros-HR,Astros-RBI,Astros-R,Astros-H,key
HOU,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,1

In [84]:
random_number = list(range(len(merge)))

In [85]:
opp_pitch_class = []
opp_pitch_class_2 = []
opp_pitch_class_3 = []

for number in random_number:
    if merge["Opposing Pitcher"][number] in df_pitch_combined.index:
        name = merge["Opposing Pitcher"][number]
        opp_pitch_class.append(df_pitch_combined.loc[name]["ERA"])
        opp_pitch_class_2.append(df_pitch_combined.loc[name]["WHIP"])
        opp_pitch_class_3.append(df_pitch_combined.loc[name]["K"])
    else:
        print(merge["Opposing Pitcher"][number])

In [29]:
opp_pitch_class = []
opp_pitch_class_2 = []
opp_pitch_class_3 = []

for number in random_number:
    if merge["Opposing Pitcher"][number] in df_pitch_combined.index:
        name = merge["Opposing Pitcher"][number]
        opp_pitch_class.append(df_pitch_combined.loc[name]["class"])
    else:
        print(merge["Opposing Pitcher"][number])

In [86]:
start_pitch_class = []
start_pitch_class_2 = []
start_pitch_class_3 = []

for number in random_number:
    if merge["Starting Pitcher"][number] in df_pitch_combined.index:
        name = merge["Starting Pitcher"][number]
        start_pitch_class.append(df_pitch_combined.loc[name]["ERA"])
        start_pitch_class_2.append(df_pitch_combined.loc[name]["WHIP"])
        start_pitch_class_3.append(df_pitch_combined.loc[name]["K"])
    else:
        print(merge["Starting Pitcher"][number])

In [30]:
start_pitch_class = []
start_pitch_class_2 = []
start_pitch_class_3 = []

for number in random_number:
    if merge["Starting Pitcher"][number] in df_pitch_combined.index:
        name = merge["Starting Pitcher"][number]
        start_pitch_class.append(df_pitch_combined.loc[name]["class"])
    else:
        print(merge["Starting Pitcher"][number])

In [87]:
merge["ERA-Starting "] = start_pitch_class
merge["ERA-Opposing"] = opp_pitch_class

merge["WHIP-Starting"] = start_pitch_class_2
merge["WHIP-Opposing"] = opp_pitch_class_2

merge["K-Starting"] = start_pitch_class_2
merge["K-Opposing"] = opp_pitch_class_2

In [88]:
merge["Starting Pitcher"] = start_pitch_class
merge["Opposing Pitcher"] = opp_pitch_class

In [89]:
merge.drop(["Starting Pitcher"], axis=1, inplace=True)
merge.drop(["Opposing Pitcher"], axis=1, inplace=True)

In [90]:
merge.head()

,Astros-SO,Astros-AVG,Astros-HBP,Astros-SH,Astros-HR,Astros-RBI,Astros-R,Astros-H,Result,SO,...,HR,RBI,R,H,ERA-Starting,ERA-Opposing,WHIP-Starting,WHIP-Opposing,K-Starting,K-Opposing
0,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,1,59.064935,...,9.119048,32.589827,34.311688,61.340909,2.690,15.7500,0.96,3.2500,0.96,3.2500
1,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,0,59.064935,...,9.119048,32.589827,34.311688,61.340909,3.090,3.0850,1.12,1.0450,1.12,1.0450
2,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,0,59.064935,...,9.119048,32.589827,34.311688,61.340909,2.550,6.6500,0.85,1.4350,0.85,1.4350
3,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,0,59.064935,...,9.119048,32.589827,34.311688,61.340909,3.745,4.1350,1.34,1.3450,1.34,1.3450
4,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,1,59.064935,...,9.119048,32.589827,34.311688,61.340909,3.090,4.9525,1.12,1.4525,1.12,1.4525

In [91]:
for col in merge.columns: 
    print(col)

Astros-SO
Astros-AVG
Astros-HBP
Astros-SH
Astros-HR
Astros-RBI
Astros-R
Astros-H
Result
SO
AVG
HBP
SH
HR
RBI
R
H
ERA-Starting
ERA-Opposing
WHIP-Starting
WHIP-Opposing
K-Starting
K-Opposing

# Running some tests

In [92]:
X = merge.copy()
X.drop(["Result"], axis=1, inplace=True)

y = merge["Result"].ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=87)

X_scaler = StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Model 1 = Random Forest Classifier

In [93]:
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

model = BalancedRandomForestClassifier(random_state=1)
model = model.fit(X_train, y_train)

y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

predictions = model.predict(X_test)
results = pd.DataFrame({"Prediction": predictions,"Actual": y_test}).reset_index(drop=True)
confusion_matrix(y_test, predictions)

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.41      0.52      0.52      0.46      0.52      0.27        21
          1       0.63      0.52      0.52      0.57      0.52      0.27        33

avg / total       0.54      0.52      0.52      0.52      0.52      0.27        54

In [94]:
predictions = model.predict(X_test)
results = pd.DataFrame({"Prediction": predictions,
                        "Actual": y_test}).reset_index(drop=True)
balanced_accuracy_score(y_test, predictions)

0.5194805194805194

## Model 2 = Decision Tree

In [162]:
from sklearn import tree, preprocessing
from sklearn.tree import DecisionTreeClassifier

model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.28      0.36      0.31        28
           1       0.60      0.51      0.55        53

    accuracy                           0.46        81
   macro avg       0.44      0.43      0.43        81
weighted avg       0.49      0.46      0.47        81

In [163]:
predictions = model.predict(X_test)
results = pd.DataFrame({"Prediction": predictions,
                        "Actual": y_test}).reset_index(drop=True)
balanced_accuracy_score(y_test, predictions)

0.433288409703504

## Model 3, neurons model(still needs work)

In [ ]:
# X_scaler = StandardScaler()
# X_scaler.fit(X_train)
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

In [155]:
y = merge["Result"].values
y = y.reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)
X_scaler = StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

ValueError: Found input variables with inconsistent numbers of samples: [216, 327]

In [156]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()
nn = Sequential()

num_units= 22
dropout_pct = 0.2

# Layer #1 - LSTM
model.add(LSTM(units=num_units, 
               return_sequences=True, 
               input_shape=(X_train.shape[1], 1))
         )
# Layer #1 dropout
model.add(Dropout(dropout_pct))

# Layer #2- LSTM
model.add(LSTM(units=num_units, return_sequences=True))
# Layer #2 dropout
model.add(Dropout(dropout_pct))

# Layer #3- LSTM
model.add(LSTM(units=num_units))
# Layer #3 dropout
model.add(Dropout(dropout_pct))

# Output
model.add(Dense(1))

In [104]:
model.compile(optimizer="adam", loss="mean_squared_error")
# model.summary()

In [105]:
model = model.fit(X_train_scaled, y_train, epochs=100, batch_size=(None, 64, 1))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [157]:
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled, y_test, verbose=2
)

2/2 - 0s - loss: 0.9939 - accuracy: 0.5000
Loss: 0.9938737154006958, Accuracy: 0.5

## Model 4 - K Neighbors

In [164]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

In [165]:
knn.fit(X_train,y_train)
predictions = knn.predict(X_test)
results = pd.DataFrame({"Prediction": predictions,
                        "Actual": y_test}).reset_index(drop=True)
balanced_accuracy_score(y_test, predictions)

0.5286388140161725

## Model 5 - XGBoost(was working, now not working, was best one)

In [96]:
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
accuracy = accuracy_score(y_test, predictions)
accuracy

0.5

In [98]:
y_pred

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [99]:
X_test

,Astros-SO,Astros-AVG,Astros-HBP,Astros-SH,Astros-HR,Astros-RBI,Astros-R,Astros-H,SO,AVG,...,HR,RBI,R,H,ERA-Starting,ERA-Opposing,WHIP-Starting,WHIP-Opposing,K-Starting,K-Opposing
112,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.860,4.440000,1.170,1.2800,1.170,1.2800
12,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,54.863095,0.215548,...,7.794643,25.130952,26.220238,52.190476,3.090,10.460000,1.120,2.2100,1.120,2.2100
173,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,2.550,4.145000,0.850,1.3500,0.850,1.3500
124,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.745,4.870000,1.340,1.3300,1.340,1.3300
80,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,60.608333,0.243292,...,11.133333,37.316667,38.758333,67.362500,3.790,3.760000,1.180,1.1800,1.180,1.1800
180,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,2.550,3.885000,0.850,1.1800,0.850,1.1800
81,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,60.608333,0.243292,...,11.133333,37.316667,38.758333,67.362500,2.550,4.145000,0.850,1.3500,0.850,1.3500
29,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.717857,0.233665,...,11.033333,41.030952,43.204762,74.601190,2.690,3.930000,0.960,1.2250,0.960,1.2250
8,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,54.863095,0.215548,...,7.794643,25.130952,26.220238,52.190476,3.275,5.120000,1.275,1.3800,1.275,1.3800
157,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,2.690,4.335000,0.960,1.3075,0.960,1.3075
205,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.851190,0.216542,...,9.020833,26.663690,27.708333,50.788690,4.025,5.645000,1.455,1.4750,1.455,1.4750
148,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,3.860,1.800000,1.170,2.0000,1.170,2.0000
92,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.790,3.900000,1.180,1.1900,1.180,1.1900
181,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,3.950,5.870000,1.100,1.5200,1.100,1.5200
212,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.851190,0.216542,...,9.020833,26.663690,27.708333,50.788690,3.745,6.245000,1.340,1.3700,1.340,1.3700
44,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,50.944816,0.223196,...,8.984114,31.122910,32.549331,57.432274,3.860,4.335000,1.170,1.2400,1.170,1.2400
45,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,50.944816,0.223196,...,8.984114,31.122910,32.549331,57.432274,3.090,2.865000,1.120,1.1100,1.120,1.1100
199,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,3.745,6.200000,1.340,1.5600,1.340,1.5600
71,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,60.794286,0.224776,...,10.224762,31.380952,32.743810,58.862857,2.550,3.615000,0.850,1.1600,0.850,1.1600
67,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,66.136364,0.220568,...,6.454545,26.204545,27.500000,60.340909,2.550,4.025000,0.850,1.4300,0.850,1.4300
66,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,66.136364,0.220568,...,6.454545,26.204545,27.500000,60.340909,2.550,4.025000,0.850,1.4300,0.850,1.4300
123,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.090,6.562500,1.120,1.6350,1.120,1.6350
129,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,2.550,5.975000,0.850,1.4650,0.850,1.4650
18,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,54.863095,0.215548,...,7.794643,25.130952,26.220238,52.190476,3.090,6.100000,1.120,1.6400,1.120,1.6400
53,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.989286,0.234244,...,10.558333,36.920238,38.475000,69.354762,2.690,8.155000,0.960,1.7000,0.960,1.7000
56,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.989286,0.234244,...,10.558333,36.920238,38.475000,69.354762,2.690,8.155000,0.960,1.7000,0.960,1.7000
32,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,52.531304,0.234981,...,8.231304,27.398261,28.466087,55.394783,3.275,3.850000,1.275,1.1800,1.275,1.1800
165,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,3.745,3.900000,1.340,1.6150,1.340,1.6150
209,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.851190,0.216542,...,9.020833,26.663690,27.708333,50.788690,2.550,7.038333,0.850,1.5450,0.850,1.5450
97,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,2.550,3.415000,0.850,1.2150,0.850,1.2150
144,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,2.690,5.975000,0.960,1.4650,0.960,1.4650
133,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,3.790,4.335000,1.180,1.3075,1.180,1.3075
13,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,54.863095,0.215548,...,7.794643,25.130952,26.220238,52.190476,2.550,6.825000,0.850,1.7700,0.850,1.7700
126,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,47.163043,0.249330,...,6.792572,29.057065,30.230978,59.859601,4.025,4.910000,1.455,1.3600,1.455,1.3600
149,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,2.690,4.335000,0.960,1.3075,0.960,1.3075
28,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.717857,0.233665,...,11.033333,41.030952,43.204762,74.601190,3.090,4.900000,1.120,1.2850,1.120,1.2850
117,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.860,3.415000,1.170,1.2150,1.170,1.2150
210,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.851190,0.216542,...,9.020833,26.663690,27.708333,50.788690,2.550,4.172500,0.850,1.2075,0.850,1.2075
24,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.717857,0.233665,...,11.033333,41.030952,43.204762,74.601190,2.550,3.815000,0.850,1.2950,0.850,1.2950
79,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,60.608333,0.243292,...,11.133333,37.316667,38.758333,67.362500,3.345,5.670000,1.070,1.6500,1.070,1.6500
152,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,3.860,4.715000,1.170,1.3150,1.170,1.3150
189,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,2.690,3.675000,0.960,1.3125,0.960,1.3125
78,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,60.608333,0.243292,...,11.133333,37.316667,38.758333,67.362500,2.690,4.010000,0.960,1.1600,0.960,1.1600
7,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,54.863095,0.215548,...,7.794643,25.130952,26.220238,52.190476,4.025,5.152500,1.455,1.4925,1.455,1.4925
171,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,3.345,9.640000,1.070,1.9900,1.070,1.9900
192,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,78.007895,0.229646,...,10.718421,37.531579,39.740789,68.806579,2.550,3.675000,0.850,1.3125,0.850,1.3125
100,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,4.000,3.415000,1.220,1.2150,1.220,1.2150
54,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.989286,0.234244,...,10.558333,36.920238,38.475000,69.354762,3.090,4.480000,1.120,1.3500,1.120,1.3500
155,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,3.745,4.715000,1.340,1.3150,1.340,1.3150
26,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.717857,0.233665,...,11.033333,41.030952,43.204762,74.601190,2.690,3.255000,0.960,0.9750,0.960,0.9750
22,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.717857,0.233665,...,11.033333,41.030952,43.204762,74.601190,3.275,3.255000,1.275,0.9750,1.275,0.9750
101,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.288043,0.226137,...,11.261957,36.794565,38.647826,65.056522,3.085,4.185000,1.045,1.2950,1.045,1.2950
137,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,55.341385,0.225651,...,8.252013,27.496779,28.735910,54.561192,2.690,3.995000,0.960,1.2650,0.960,1.2650
52,56.95,0.239085,3.096429,0.564286,11.982143,40.289286,41.805952,71.295238,63.989286,0.234244,...,10.558333,36.920238,38.475000,69.354762,2.690,7.250000,0.960,1.7400,0.960,1.7400

# Defining Functions

In [52]:
starting_pitcher = input("Enter Astros Starting Pitcher: ")
opposing_pitcher = input("Enter Opposing Starting Pitcher: ")

Enter Astros Starting Pitcher:  Justin Verlander
Enter Opposing Starting Pitcher:  Colt

In [51]:
def determine_who_wins(starting_pitcher, opposing_pitcher):
    pitch_stat = []
    pitch_stat_2 = []
    pitch_stat_3 = []
    
    if starting_pitcher in df_pitch_combined.index:
        
        pitch_stat.append(df_pitch_combined.loc[starting_pitcher]["ERA"])
        pitch_stat_2.append(df_pitch_combined.loc[starting_pitcher]["WHIP"])
        pitch_stat_3.append(df_pitch_combined.loc[starting_pitcher]["K"])
        
        
        
    opp_pitch_stat = []
    opp_pitch_stat_2 = []
    opp_pitch_stat_3 = []
    
    if opposing_pitcher in df_pitch_combined.index:
       
        opp_pitch_stat.append(df_pitch_combined.loc[opposing_pitcher]["ERA"])
        opp_pitch_stat_2.append(df_pitch_combined.loc[opposing_pitcher]["WHIP"])
        opp_pitch_stat_3.append(df_pitch_combined.loc[opposing_pitcher]["K"])
    
    
    
    result = model.predict(input_data)
    return result

Cookies

In [97]:
model

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)